options = 
{
	{
		default = 1,
		label = "Survival: Build Time", 
		help = "Length of initial building time.", 
		key = 'opt_Survival_BuildTime',
		pref = 'opt_Survival_BuildTime', 
		values = { 
			{text = "0:00 Default",help = "", key = 0, },
			{text = "0:30",help = "", key = 30, }, 
			{text = "1:00",help = "", key = 60, }, 
			{text = "1:30",help = "", key = 90, }, 
			{text = "2:00",help = "", key = 120, }, 
			{text = "2:30",help = "", key = 150, }, 
			{text = "3:00",help = "", key = 180, }, 
			{text = "4:00",help = "", key = 240, }, 
			{text = "5:00",help = "", key = 300, },
			{text = "6:00",help = "", key = 360, },
			{text = "7:00",help = "", key = 420, },
			{text = "8:00",help = "", key = 480, },
			{text = "9:00",help = "", key = 540, },
			{text = "10:00",help = "", key = 600, },
		}, 
	},
	{
		default = 7,
		label = "Survival: Navy Interval", 
		help = "Time between Navy Spawns.", 
		key = 'opt_Survival_NavySpawnInterval',
		pref = 'opt_Survival_NavySpawnInterval', 
		values = { 
			{text = "1 Seconds Super Impossible!",help = "", key = 1, }, 
			{text = "1.5 Seconds",help = "", key = "1.5", }, 
			{text = "2 Seconds",help = "", key = 2, }, 
			{text = "2.5 Seconds",help = "", key = "2.5", }, 
			{text = "3 Seconds",help = "", key = 3, },
			{text = "3.5 Seconds",help = "", key = "3.5", },
			{text = "4 Seconds",help = "", key = 4, },
			{text = "4.5 Seconds",help = "", key = "4.5", },
			{text = "5 Seconds",help = "", key = 5, },
			{text = "5.5 Seconds",help = "", key = "5.5", },
			{text = "6 Seconds",help = "", key = 6, },
			{text = "6.5 Seconds",help = "", key = "6.5", },
			{text = "7 Seconds Super Easy!",help = "", key = 7, },
		}, 
	},
	{
		default = 7,
		label = "Survival: Gate Interval", 
		help = "Time between Gate Spawns.", 
		key = 'opt_Survival_GateSpawnInterval',
		pref = 'opt_Survival_GateSpawnInterval', 
		values = { 
			{text = "7 Seconds Super Impossible!",help = "", key = 7, }, 
			{text = "7.5 Seconds",help = "", key = "7.5", }, 
			{text = "8 Seconds",help = "", key = 8, }, 
			{text = "8.5 Seconds",help = "", key = "8.5", }, 
			{text = "9 Seconds",help = "", key = 9, },
			{text = "9.5 Seconds",help = "", key = "9.5", },
			{text = "10 Seconds",help = "", key = 10, },
			{text = "10.5 Seconds",help = "", key = "10.5", },
			{text = "11 Seconds",help = "", key = 11, },
			{text = "11.5 Seconds",help = "", key = "11.5", },
			{text = "12 Seconds",help = "", key = 12, },
			{text = "12.5 Seconds",help = "", key = "12.5", },
			{text = "13 Seconds Super Easy!",help = "", key = 13, },
		}, 
	},
	{
		default = 7,
		label = "Survival: Land Interval", 
		help = "Time between Land Spawns.", 
		key = 'opt_Survival_LandSpawnInterval',
		pref = 'opt_Survival_LandSpawnInterval', 
		values = { 
			{text = "1 Seconds Super Impossible!",help = "", key = 1, }, 
			{text = "1.5 Seconds",help = "", key = "1.5", }, 
			{text = "2 Seconds",help = "", key = 2, }, 
			{text = "2.5 Seconds",help = "", key = "2.5", }, 
			{text = "3 Seconds",help = "", key = 3, },
			{text = "3.5 Seconds",help = "", key = "3.5", },
			{text = "4 Seconds",help = "", key = 4, },
			{text = "4.5 Seconds",help = "", key = "4.5", },
			{text = "5 Seconds",help = "", key = 5, },
			{text = "5.5 Seconds",help = "", key = "5.5", },
			{text = "6 Seconds",help = "", key = 6, },
			{text = "6.5 Seconds",help = "", key = "6.5", },
			{text = "7 Seconds Super Easy!",help = "", key = 7, },
		}, 
	},
	{
		default = 7,
		label = "Survival: Drop Interval", 
		help = "Time between Drop Spawns.", 
		key = 'opt_Survival_DropSpawnInterval',
		pref = 'opt_Survival_DropSpawnInterval', 
		values = { 
			{text = "1 Seconds Super Impossible!",help = "", key = 1, }, 
			{text = "1.5 Seconds",help = "", key = "1.5", }, 
			{text = "2 Seconds",help = "", key = 2, }, 
			{text = "2.5 Seconds",help = "", key = "2.5", }, 
			{text = "3 Seconds",help = "", key = 3, },
			{text = "3.5 Seconds",help = "", key = "3.5", },
			{text = "4 Seconds",help = "", key = 4, },
			{text = "4.5 Seconds",help = "", key = "4.5", },
			{text = "5 Seconds",help = "", key = 5, },
			{text = "5.5 Seconds",help = "", key = "5.5", },
			{text = "6 Seconds",help = "", key = 6, },
			{text = "6.5 Seconds",help = "", key = "6.5", },
			{text = "7 Seconds Super Easy!",help = "", key = 7, },
		}, 
	},
	{
		default = 1,
		label = "Survival: All Factions",
		help = "When enabled, each player get extra engineers or ACUs",
		key = 'opt_SurvivalAllFactions',
		pref = 'opt_SurvivalAllFactions',
		values = {
			{ text = "Disabled", help = "No extra units", key = 0, },
			{ text = "Enabled - engineers", help = "Each player gets 3 extra T1 engineers", key = 1, },
			{ text = "Enabled - ACUs", help = "Each player gets 3 extra ACUs", key = 2, },
		},
	},
	{
		default = 1,
		label = "Survival: Unit Wrecks",
		help = "When enabled, wrecks will be off",
		key = 'opt_Wrecks',
		pref = 'opt_Wrecks',
		values = {
			{ text = "Wrecks On", help = "Wrecks On", key = 0, },
			{ text = "Wrecks Off", help = "Wrecks Off", key = 1, },
			
		},
	},
	{
		default = 7,
		label = "Survival: Health Multiplier",
		help = "Health of the (enemy) survival units",
		key = 'opt_Survival_HealthMultiplier',
		pref = 'opt_Survival_HealthMultiplier',
		values = {
			{ text = "10 percent", help = "10 percent", key = 0.1, },
			{ text = "30 percent", help = "30 percent", key = 0.3, },
			{ text = "50 percent", help = "50 percent", key = 0.5, },
			{ text = "70 percent", help = "70 percent", key = 0.7, },
			{ text = "80 percent", help = "80 percent", key = 0.8, },
			{ text = "90 percent", help = "90 percent", key = 0.9, },
			{ text = "100 percent", help = "100 percent", key = 1, },
			{ text = "110 percent", help = "110 percent", key = 1.1, },
			{ text = "120 percent", help = "120 percent", key = 1.2, },
			{ text = "130 percent", help = "130 percent", key = 1.3, },
			{ text = "140 percent", help = "140 percent", key = 1.4, },
			{ text = "150 percent", help = "150 percent", key = 1.5, },
			{ text = "160 percent", help = "160 percent", key = 1.6, },
			{ text = "170 percent", help = "170 percent", key = 1.7, },
			{ text = "180 percent", help = "180 percent", key = 1.8, },
			{ text = "190 percent", help = "190 percent", key = 1.9, },
			{ text = "200 percent", help = "200 percent", key = 2, },
			{ text = "210 percent", help = "210 percent", key = 2.1, },
			{ text = "225 percent", help = "225 percent", key = 2.25, },
			{ text = "250 percent", help = "250 percent", key = 2.5, },
			{ text = "300 percent", help = "300 percent", key = 3, },
			{ text = "305 percent", help = "305 percent", key = 3.05, },
			{ text = "310 percent", help = "310 percent", key = 3.1, },
			{ text = "320 percent", help = "320 percent", key = 3.2, },
			{ text = "330 percent", help = "330 percent", key = 3.3, },
			{ text = "340 percent", help = "340 percent", key = 3.4, },
			{ text = "350 percent", help = "350 percent", key = 3.5, },
			{ text = "360 percent", help = "360 percent", key = 3.6, },
			{ text = "370 percent", help = "370 percent", key = 3.7, },
			{ text = "380 percent", help = "380 percent", key = 3.8, },
			{ text = "390 percent", help = "390 percent", key = 3.9, },
			{ text = "400 percent", help = "400 percent", key = 4, },
			{ text = "410 percent", help = "410 percent", key = 4.1, },
			{ text = "420 percent", help = "420 percent", key = 4.2, },
			{ text = "450 percent", help = "450 percent", key = 4.5, },
			{ text = "500 percent", help = "500 percent", key = 5, },
			{ text = "750 percent", help = "750 percent", key = 7.5, },
			{ text = "10x", help = "10x", key = 10, },
			{ text = "25x", help = "25x", key = 25, },
			{ text = "100x", help = "100x", key = 100, },
			{ text = "500x", help = "500x", key = 500, },
			{ text = "1000x", help = "1000x", key = 1000, },
			{ text = "10000x", help = "Labs are the new GCs", key = 10000, },
		},
	},
	{
		default = 7,
		label = "Survival: Damage Multiplier",
		help = "Damage dealt by the (enemy) survival units",
		key = 'opt_Survival_DamageMultiplier',
		pref = 'opt_Survival_DamageMultiplier',
		values = {
			{ text = "10 percent", help = "10 percent", key = 0.1, },
			{ text = "30 percent", help = "30 percent", key = 0.3, },
			{ text = "50 percent", help = "50 percent", key = 0.5, },
			{ text = "70 percent", help = "70 percent", key = 0.7, },
			{ text = "80 percent", help = "80 percent", key = 0.8, },
			{ text = "90 percent", help = "90 percent", key = 0.9, },
			{ text = "100 percent", help = "100 percent", key = 1, },
			{ text = "110 percent", help = "110 percent", key = 1.1, },
			{ text = "120 percent", help = "120 percent", key = 1.2, },
			{ text = "130 percent", help = "130 percent", key = 1.3, },
			{ text = "140 percent", help = "140 percent", key = 1.4, },
			{ text = "150 percent", help = "150 percent", key = 1.5, },
			{ text = "160 percent", help = "160 percent", key = 1.6, },
			{ text = "170 percent", help = "170 percent", key = 1.7, },
			{ text = "180 percent", help = "180 percent", key = 1.8, },
			{ text = "190 percent", help = "190 percent", key = 1.9, },
			{ text = "200 percent", help = "200 percent", key = 2, },
			{ text = "210 percent", help = "210 percent", key = 2.1, },
			{ text = "225 percent", help = "225 percent", key = 2.25, },
			{ text = "250 percent", help = "250 percent", key = 2.5, },
			{ text = "300 percent", help = "300 percent", key = 3, },
			{ text = "305 percent", help = "305 percent", key = 3.05, },
			{ text = "310 percent", help = "310 percent", key = 3.1, },
			{ text = "320 percent", help = "320 percent", key = 3.2, },
			{ text = "330 percent", help = "330 percent", key = 3.3, },
			{ text = "340 percent", help = "340 percent", key = 3.4, },
			{ text = "350 percent", help = "350 percent", key = 3.5, },
			{ text = "360 percent", help = "360 percent", key = 3.6, },
			{ text = "370 percent", help = "370 percent", key = 3.7, },
			{ text = "380 percent", help = "380 percent", key = 3.8, },
			{ text = "390 percent", help = "390 percent", key = 3.9, },
			{ text = "400 percent", help = "400 percent", key = 4, },
			{ text = "410 percent", help = "410 percent", key = 4.1, },
			{ text = "420 percent", help = "420 percent", key = 4.2, },
			{ text = "450 percent", help = "450 percent", key = 4.5, },
			{ text = "500 percent", help = "500 percent", key = 5, },
			{ text = "750 percent", help = "750 percent", key = 7.5, },
			{ text = "10x", help = "10x", key = 10, },
			{ text = "25x", help = "25x", key = 25, },
			{ text = "100x", help = "100x", key = 100, },
			{ text = "500x", help = "500x", key = 500, },
			{ text = "1000x", help = "1000x", key = 1000, },
			{ text = "10000x", help = "Because scouts should obviously one-shot ACUs!", key = 10000, },
		},
	},
};
